-- 1. 启用 UUID 扩展（可选，虽然当前设计用 Int/Varchar，但推荐 UUID）
create extension if not exists "uuid-ossp";

-- 2. 桌子表 (Table)
create table public.tables (
    table_id varchar primary key, -- 例如 'A01', 'B02'
    current_order_group_id int,   -- 指向当前活跃的 order_groups.id
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 订单组表 (OrderGroup) - 用于聚合一次用餐的所有子订单
create table public.order_groups (
    id bigint generated by default as identity primary key,
    table_id varchar not null references public.tables(table_id),
    status varchar not null check (status in ('active', 'completed', 'cancelled')), -- 未结/已结
    total_amount numeric default 0, -- 缓存总金额
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 子订单表 (Order) - 每次扫码下单生成一条
create table public.orders (
    id bigint generated by default as identity primary key,
    order_group_id bigint not null references public.order_groups(id),
    items jsonb not null, -- 存储快照: [{id, name, qty, price, options}]
    subtotal numeric not null,
    sequence_number int not null default 1, -- 第几次下单
    status varchar default 'pending', -- 制作状态: pending, cooking, done
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. 菜品表 (Dish)
create table public.dishes (
    id bigint generated by default as identity primary key,
    name varchar not null,
    price numeric not null,
    category varchar not null,
    image_url varchar,
    options jsonb default '[]'::jsonb, -- 例如 [{"name": "微辣"}, {"name": "加蛋", "price": 2}]
    is_available boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. 建立外键关联以确保数据完整性
alter table public.tables 
add constraint fk_current_group 
foreign key (current_order_group_id) 
references public.order_groups(id);

-- 7. 插入一些测试数据
insert into public.dishes (name, price, category, image_url, options) values
('招牌红烧肉', 58, '热菜', 'https://placehold.co/200x200?text=Pork', '[{"name":"加鹌鹑蛋","price":5}]'),
('清炒时蔬', 28, '素菜', 'https://placehold.co/200x200?text=Veg', '[]'),
('冰镇可乐', 5, '饮料', 'https://placehold.co/200x200?text=Coke', '[{"name":"去冰","price":0}]'),
('米饭', 2, '主食', 'https://placehold.co/200x200?text=Rice', '[]');

insert into public.tables (table_id) values ('A01'), ('A02'), ('B01');