-- 1. 启用 UUID 扩展（可选，虽然当前设计用 Int/Varchar，但推荐 UUID）
create extension if not exists "uuid-ossp";

-- 2. 桌子表 (Table)
create table public.tables (
    table_id varchar primary key, -- 例如 'A01', 'B02'
    current_order_group_id int,   -- 指向当前活跃的 order_groups.id
    status varchar default 'free', -- 桌台状态: free, occupied
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 订单组表 (OrderGroup) - 用于聚合一次用餐的所有子订单
create table public.order_groups (
    id bigint generated by default as identity primary key,
    table_id varchar not null references public.tables(table_id),
    status varchar not null check (status in ('active', 'completed', 'cancelled')), -- 未结/已结
    total_amount numeric default 0, -- 缓存总金额
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 子订单表 (Order) - 每次扫码下单生成一条
create table public.orders (
    id bigint generated by default as identity primary key,
    order_group_id bigint not null references public.order_groups(id),
    items jsonb not null, -- 存储快照: [{id, name, qty, price, options}]
    subtotal numeric not null,
    sequence_number int not null default 1, -- 第几次下单
    status varchar default 'pending', -- 制作状态: pending, cooking, done
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. 分类表 (Category)
create table public.categories (
    id bigint generated by default as identity primary key,
    name varchar not null unique,
    icon varchar default '🍽️', -- 图标 emoji
    sort_order int default 0,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. 菜品表 (Dish) - 已扩展支持更多字段
create table public.dishes (
    id bigint generated by default as identity primary key,
    name varchar not null,
    description text, -- 菜品描述
    price numeric not null,
    original_price numeric, -- 原价（用于促销显示）
    category varchar not null,
    image_url varchar,
    -- options 格式: {"specs": [{"name": "辣度", "required": false, "multi": false, "values": [{"name": "微辣", "price": 0}]}]}
    options jsonb default '{"specs": []}'::jsonb, 
    is_available boolean default true, -- 上架状态
    is_recommended boolean default false, -- 推荐菜品
    sort_order int default 0, -- 排序权重
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. 建立外键关联以确保数据完整性
alter table public.tables 
add constraint fk_current_group 
foreign key (current_order_group_id) 
references public.order_groups(id);

-- 8. 创建索引优化查询性能
create index idx_dishes_category on public.dishes(category);
create index idx_dishes_sort_order on public.dishes(sort_order);
create index idx_dishes_available on public.dishes(is_available);
create index idx_categories_sort_order on public.categories(sort_order);

-- 9. 插入分类数据
insert into public.categories (name, icon, sort_order) values
('汤面类', '🍜', 1),
('拌面类', '🥢', 2),
('外加类', '➕', 3),
('面疙瘩类', '🥟', 4),
('饮料类', '🥤', 5)
on conflict (name) do nothing;

-- 10. 插入菜品数据
-- 汤面类
insert into public.dishes (name, price, category) values
('青菜肉丝面', 15, '汤面类'),
('青菜鸡蛋面', 15, '汤面类'),
('片儿川', 15, '汤面类'),
('大排面', 24, '汤面类'),
('小排面', 26, '汤面类'),
('牛肉面', 26, '汤面类'),
('肚片面', 26, '汤面类'),
('大肠面', 26, '汤面类'),
('酱香肠面', 26, '汤面类'),
('青菜河虾面', 26, '汤面类'),
('三鲜面', 28, '汤面类'),
('腰花面', 26, '汤面类'),
('海鲜面', 30, '汤面类'),
('河虾小排面', 35, '汤面类'),
('河虾大排面', 35, '汤面类'),
('河虾牛肉面', 35, '汤面类'),
('河虾肚片面', 35, '汤面类'),
('特色海鲜面', 45, '汤面类')
on conflict do nothing;

-- 拌面类
insert into public.dishes (name, price, category) values
('葱油拌面', 12, '拌面类'),
('油渣拌面', 15, '拌面类'),
('小排拌面', 26, '拌面类'),
('肚片拌面', 26, '拌面类'),
('牛肉拌面', 26, '拌面类'),
('河虾拌面', 26, '拌面类')
on conflict do nothing;

-- 面疙瘩类
insert into public.dishes (name, price, category) values
('青菜肉丝面疙瘩', 17, '面疙瘩类'),
('笋干肉丝面疙瘩', 17, '面疙瘩类'),
('三鲜面疙瘩', 30, '面疙瘩类'),
('海鲜面疙瘩', 30, '面疙瘩类'),
('河虾笋干菜面疙瘩', 30, '面疙瘩类')
on conflict do nothing;

-- 外加类
insert into public.dishes (name, price, category) values
('大排', 12, '外加类'),
('小排', 15, '外加类'),
('河虾', 15, '外加类'),
('鸡蛋', 2, '外加类'),
('加面', 2, '外加类'),
('油渣', 3, '外加类')
on conflict do nothing;

-- 饮料类
insert into public.dishes (name, price, category) values
('李子园甜牛奶', 6, '饮料类'),
('红牛', 7, '饮料类'),
('王老吉凉茶', 5, '饮料类'),
('柚香谷', 7, '饮料类'),
('喜爱果园', 6, '饮料类'),
('可口可乐', 4, '饮料类'),
('农夫山泉茶π', 6, '饮料类'),
('康师傅矿泉水', 3, '饮料类'),
('李子园草莓', 6, '饮料类'),
('啤酒瓶装', 7, '饮料类'),
('椰汁', 5, '饮料类'),
('荔枝饮料', 5, '饮料类')
on conflict do nothing;

-- 11. 插入桌台数据
insert into public.tables (table_id) values 
('A01'), ('A02'), ('A03'), ('A04'), ('A05'), ('A06');
